(function () {
  var status=document.getElementById('status'),loginShell=document.getElementById('login-shell'),loginForm=document.getElementById('login-form'),appShell=document.getElementById('app-shell'),nav=document.getElementById('bottom-nav'),list=document.getElementById('radar-list'),meta=document.getElementById('radar-meta'),api=String(window.TURNIO_EXTERNAL_API||'').replace(/\/$/,''),clientKey='turnio_external_client_id',sessionKey='turnio_external_session_token',mode='TODOS',radar=[];
  var esc=function(s){return String(s==null?'':s).replace(/[&<>'"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c];});};
  function plainText(s){var text=String(s==null?'':s),el=document.createElement('div');for(var i=0;i<3&&/[<&]/.test(text);i++){el.innerHTML=text;text=el.textContent||el.innerText||'';}return text.replace(/\s+/g,' ').trim();}
  function clientId(){var id=localStorage.getItem(clientKey)||'';if(!/^[A-Za-z0-9_-]{24,128}$/.test(id)){id=Array.from(crypto.getRandomValues(new Uint8Array(24)),function(b){return b.toString(16).padStart(2,'0');}).join('');localStorage.setItem(clientKey,id);}return id;}
  async function call(accion,extra){var r=await fetch(api+'/api/turnio',{method:'POST',headers:{'Content-Type':'application/json'},cache:'no-store',body:JSON.stringify(Object.assign({accion:accion,clientId:clientId(),sessionToken:localStorage.getItem(sessionKey)||''},extra||{}))}),d;try{d=await r.json();}catch(_){throw new Error('Respuesta no v\u00e1lida del servicio.');}if(!r.ok||d.ok===false||d.exito===false)throw new Error(d.error||'No se pudo completar la operaci\u00f3n.');return d;}
  function setStatus(kind,text){status.className='status '+kind;status.textContent=text;}
  function toast(text){var t=document.getElementById('toast');t.textContent=text;t.classList.add('show');setTimeout(function(){t.classList.remove('show');},2800);}
  function go(screen){document.querySelectorAll('.screen').forEach(function(s){s.classList.remove('active');});document.getElementById('screen-'+screen).classList.add('active');document.querySelectorAll('.nav-item').forEach(function(b){b.classList.toggle('active',b.dataset.go===screen);});if(screen==='radar'&&!radar.length)loadRadar();window.scrollTo({top:0,behavior:'smooth'});}
  function showApp(persona){loginShell.hidden=true;appShell.hidden=false;nav.hidden=false;var nombre=(persona&&persona.nombre)||'usuario',email=(persona&&persona.email)||document.getElementById('email').value||'';document.getElementById('welcome-name').textContent='Hola, '+nombre+'.';document.getElementById('user-email').textContent=email;document.getElementById('profile-email').textContent=email;loadRadar();}
  function typeOf(a){var x=String(a.tipo||'');return x.indexOf('ALERTA')>=0?'grave':x.indexOf('AVISO')>=0?'warning':'';}
  function filtered(){var q=String(document.getElementById('search').value||'').toLowerCase();return radar.filter(function(a){return !q||JSON.stringify(a).toLowerCase().indexOf(q)>=0;});}
  function render(){var a=filtered(),total=radar[0]&&Number(radar[0].totalActivos),incid=radar[0]&&Number(radar[0].totalIncidencias),home=document.getElementById('home-radar');meta.textContent='\u00daltima carga: '+new Date().toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit',second:'2-digit'});if(!radar.length||radar.length===1&&/LIMPIA/i.test(String(radar[0].tipo||''))){var msg=radar[0]&&radar[0].mensaje||'Red operando con normalidad.';list.innerHTML='<div class="empty clean">'+esc(msg)+'</div>';home.textContent=msg;return;}home.innerHTML='<b>'+esc(String(isFinite(total)?total:radar.length))+' trenes analizados</b> &middot; '+esc(String(isFinite(incid)?incid:radar.length))+' incidencias';var head=isFinite(total)?'<div class="summary-chips"><span>&#128642; '+total+' trenes</span><span class="incident">&#9888; '+(isFinite(incid)?incid:radar.length)+' incidencias</span></div>':'';list.innerHTML=head+a.map(function(x){var delay=Number(x.retrasoNum||0),cls=typeOf(x),tren=String(x.codTren||'').replace(/[^0-9]/g,''),trip=String(x.tripId||x.trip_id||''),linea=plainText(x.linea||('Circ. '+tren));return '<article class="alert '+cls+'" data-cod="'+esc(tren)+'" data-trip="'+esc(trip)+'"><div class="alert-head"><span>&#128308; '+esc(x.tipo||'AVISO')+'</span><span>&#128338; '+esc(x.hora||'')+'</span></div><div class="train">&#9642; '+esc(linea)+'</div><p class="message">'+esc(x.mensaje||('Demora '+(delay>=0?'+':'')+delay+' min.'))+'</p><div class="alert-bottom"><span>&#8618; Pulsa para ver la marcha</span><button class="generate" type="button">&#128172; Generar Aviso</button></div><div class="marcha-panel" hidden></div></article>';}).join('');}
  function labelStatus(s){return s==='STOPPED_AT'?'&#128205; Posici\u00f3n en estaci\u00f3n':s==='INCOMING_AT'?'&#128646; Llegando a estaci\u00f3n':s==='IN_TRANSIT_TO'?'&#128642; En circulaci\u00f3n':'&#128642; Activo';}
  function renderMarcha(panel,m){if(!m||!m.ok){panel.innerHTML='<div class="marcha-empty">'+esc((m&&m.mensaje)||'Tren no localizado en los datos en vivo.')+'</div>';return;}var retraso=Number(m.retrasoMin||0),paradas=Array.isArray(m.paradas)?m.paradas:[];var ruta='';if(m.origen||m.destino){ruta='<div class="marcha-route">'+esc(m.origen||'—')+(m.hOrig?' ('+esc(m.hOrig)+')':'')+' \u2794 '+esc(m.destino||'—')+(m.hDest?' programada '+esc(m.hDest):'')+(m.hDestPrevista?' \u00b7 prevista '+esc(m.hDestPrevista):'')+'</div>';}var retTxt=m.retrasoOperativoTexto||(retraso>0?('+'+retraso+' min'+(m.hDestPrevista&&m.destino?' \u00b7 Llegada prevista a '+m.destino+': '+m.hDestPrevista+'h':'')):'Puntual');var rows=paradas.slice(0,24).map(function(p){var cl=p.esActual?'actual':p.esPasada?'pasada':'';var icon=p.esActual?'&#128205;':p.esPasada?'&#10003;':'&#9675;';return '<div class="marcha-step '+cl+'"><b>'+esc(p.horaEst||p.horaProgramada||'--:--')+'</b><span>'+icon+' '+esc(p.nombre||'Parada')+(Number(p.delayMin||0)>0?' <em>+'+Number(p.delayMin)+' min</em>':'')+'</span></div>';}).join('');panel.innerHTML='<div class="marcha-head"><strong>&#128225; Marcha en vivo &middot; Tren '+esc(m.numTren||'')+'</strong><span>'+labelStatus(m.status)+'</span></div>'+ruta+'<div class="marcha-kpis"><span>'+(retraso>0?'&#9201; '+esc(retTxt):'&#9989; Puntual')+'</span><span>'+esc(m.stopActualNombre||'Posici\u00f3n disponible')+'</span></div>'+(rows?'<div class="marcha-list">'+rows+'</div>':'<div class="marcha-empty">Sin paradas disponibles en el feed.</div>')+'<div class="marcha-source">Fuente: Renfe GTFS-RT</div>';}
  async function abrirMarcha(card){var panel=card.querySelector('.marcha-panel');if(!panel)return;if(!panel.hidden){panel.hidden=true;return;}var tren=String(card.dataset.cod||'');if(!tren){toast('No hay n\u00famero de tren para consultar.');return;}panel.hidden=false;panel.innerHTML='<div class="marcha-empty">Consultando marcha en vivo...</div>';try{var data=await call('marcha',{codTren:tren,tripId:String(card.dataset.trip||'')});renderMarcha(panel,data.marcha);}catch(e){panel.innerHTML='<div class="marcha-empty error-text">'+esc(e.message)+'</div>';}}
  async function loadRadar(){list.innerHTML='<div class="empty">Actualizando Radar...</div>';try{var data=await call('radar',{modo:mode,region:document.getElementById('region').value});radar=Array.isArray(data.alertas)?data.alertas:[];render();}catch(e){list.innerHTML='<div class="empty">'+esc(e.message)+'</div>';if(/sesi\u00f3n|caducada/i.test(e.message)){localStorage.removeItem(sessionKey);appShell.hidden=true;nav.hidden=true;loginShell.hidden=false;loginForm.hidden=false;}}}
  async function init(){if(!api){setStatus('error','Puente externo pendiente de configurar.');return;}try{var r=await fetch(api+'/api/health',{cache:'no-store'}),d=await r.json();if(!r.ok||!d.ok||!d.configured)throw 0;setStatus('ready','Conexi\u00f3n externa preparada.');if(localStorage.getItem(sessionKey)){try{var x=await call('sesion');showApp(x.persona);return;}catch(_){localStorage.removeItem(sessionKey);}}loginForm.hidden=false;}catch(_){setStatus('error','No se ha podido conectar con el entorno externo.');}}
  loginForm.addEventListener('submit',async function(e){e.preventDefault();setStatus('pending','Validando acceso...');try{var d=await call('iniciar_pruebas',{email:document.getElementById('email').value.trim(),pin:document.getElementById('pin').value});if(!d.token)throw new Error('No se ha creado la sesi\u00f3n.');localStorage.setItem(sessionKey,d.token);setStatus('ready','Sesi\u00f3n iniciada.');showApp(d.persona);}catch(err){setStatus('error',err.message);}});
  document.querySelectorAll('[data-go]').forEach(function(b){b.addEventListener('click',function(){go(b.dataset.go);});});document.querySelectorAll('[data-coming]').forEach(function(b){b.addEventListener('click',function(){toast(b.dataset.coming+' se incorporar\u00e1 en el siguiente bloque.');});});document.querySelectorAll('.filter').forEach(function(b){b.addEventListener('click',function(){mode=b.dataset.mode;document.querySelectorAll('.filter').forEach(function(x){x.classList.toggle('active',x===b);});loadRadar();});});document.getElementById('region').addEventListener('change',loadRadar);document.getElementById('search').addEventListener('input',render);document.getElementById('logout').addEventListener('click',function(){localStorage.removeItem(sessionKey);appShell.hidden=true;nav.hidden=true;loginShell.hidden=false;loginForm.hidden=false;toast('Sesi\u00f3n de pruebas cerrada.');});list.addEventListener('click',function(e){var generate=e.target.closest('.generate');if(generate){e.stopPropagation();toast('La generaci\u00f3n de avisos se incorporar\u00e1 tras migrar su API.');return;}var card=e.target.closest('.alert');if(card)abrirMarcha(card);});init();
}());
